### PR TITLE
Clean select_timeperiod: avoid helper variable

### PR DESCRIPTION
**Pull request by hsonne**
Where is the dev branch?

### CODE REVIEW

**Comment by mrustl** [comment]
"dev" - not there yet. But I am currently on a feature branch close to be commited to master....

https://github.com/KWB-R/kwb.heatsine/tree/data-workflow

**Comment by hsonne** [comment]
Should I target PRs (code cleaning) to the feature branch?

**Comment by mrustl** [comment]
I merged your other pull request to data-workflow and will now merge it to master.

**Comment by mrustl** [comment]
And you change the pull request to branch "data-workflow" ?

**Comment by hsonne** [comment]
ok

**Pull request closed without merging**
